namespace PurrPurrCoffee
{
    using UnityEngine;
    using TMPro;

    /// <summary>
    /// Generated by AI
    /// </summary>
    public class MoneyPopup : MonoBehaviour
    {
        public TextMeshProUGUI text;
        public CanvasGroup canvasGroup;

        [Header("Animation Settings")]
        public float floatUpDistance = 50f;
        public float duration = 1.5f;

        private Vector3 startPos;
        private Vector3 endPos;

        public void Show(int amount)
        {
            text.text = $"+{amount}$";
            startPos = transform.localPosition;
            endPos = startPos + Vector3.up * floatUpDistance;
            canvasGroup.alpha = 1f;
            StartCoroutine(Animate());
        }

        private System.Collections.IEnumerator Animate()
        {
            float time = 0f;

            while (time < duration)
            {
                float t = time / duration;
                transform.localPosition = Vector3.Lerp(startPos, endPos, t);
                canvasGroup.alpha = Mathf.Lerp(1f, 0f, t);
                time += Time.deltaTime;
                yield return null;
            }

            Destroy(gameObject);
        }
    }
}
